version: "3.1"

services:
  # kavanet-interconnector:
  #   container_name: kavanet-interconnector
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   image: kavanet-interconnector:latest
  #   networks:
  #     - proxynet

  mosquitto:
    image: eclipse-mosquitto:1.6
    hostname: mosquitto
    container_name: mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
    # depends_on:
    #   - influxdb
    restart: always
    volumes:
      - mosquitto:/mosquitto/data
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
    networks:
      - proxynet

networks:
  proxynet:
    name: kavanet-network

volumes:
  mosquitto:
