name: printer-proxy

namespace: proxies

deployment:
  - name: printer-proxy
    image: nginx
    ports:
    - port: 80
    volumes:
      - name: printer-nginx-settings
        type: config
        path: /etc/nginx/conf.d/

service:
  clusterIP:
    - name: printer-proxy
      selector: printer-proxy
      ports:
      - port: 80


configmap:
  - name: printer-nginx-settings
    file: config/proxy.conf

  - name: liam-printer-nginx-settings
    file: config/liamProxy.conf

ingress:
  - name: printer-proxy
    selector: printer-proxy
    path: /
    port: 80
    host: printer.kavanet.io

  - name: liam-printer-proxy
    selector: liam-printer-proxy
    path: /
    port: 80
    host: liam.printer.kavanet.io
