---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: ip-pool
  namespace: metallb-system
spec:
  autoAssign: true
  addresses:
  - 192.168.1.60-192.168.1.80

---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: ip-pool
  namespace: metallb-system
spec:
  ipAddressPools:
  - ip-pool

