####################################
#
#     ######                                                                       
#     #     # ###### #####  #       ####  #   # #    # ###### #    # #####  
#     #     # #      #    # #      #    #  # #  ##  ## #      ##   #   #    
#     #     # #####  #    # #      #    #   #   # ## # #####  # #  #   #    
#     #     # #      #####  #      #    #   #   #    # #      #  # #   #    
#     #     # #      #      #      #    #   #   #    # #      #   ##   #    
#     ######  ###### #      ######  ####    #   #    # ###### #    #   #     
#
####################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-deployment
  namespace: grafana
  labels:
    app: prometheus
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
      - name: prometheus
        image: prom/prometheus
        volumeMounts:
          - name: config-volume
            mountPath: /etc/prometheus/prometheus.yml
            subPath: prometheus.yaml
        ports:
        - containerPort: 9090
      volumes:
        - name: config-volume
          configMap:
           name: prometheus-config

####################################
#
#   #####                                   #     #                       
#  #     #  ####  #    # ###### #  ####     ##   ##   ##   #####  
#  #       #    # ##   # #      # #    #    # # # #  #  #  #    # 
#  #       #    # # #  # #####  # #         #  #  # #    # #    # 
#  #       #    # #  # # #      # #  ###    #     # ###### #####  
#  #     # #    # #   ## #      # #    #    #     # #    # #      
#   #####   ####  #    # #      #  ####     #     # #    # #     
#
####################################
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: grafana
data:
  prometheus.yaml: |
    global:
      scrape_interval:     15s
      external_labels:
        monitor: 'k3s-monitor'
    scrape_configs:
      - job_name: 'prometheus'
        scrape_interval: 5s
        static_configs:
          - targets: ['localhost:9090']
      - job_name: 'K3S'
        static_configs:
          - targets: ['192.168.1.42:9100', '192.168.1.43:9100']

####################################
#
#     #####                                       
#    #     # ###### #####  #    # #  ####  ###### 
#    #       #      #    # #    # # #    # #      
#     #####  #####  #    # #    # # #      #####  
#          # #      #####  #    # # #      #      
#    #     # #      #   #   #  #  # #    # #      
#     #####  ###### #    #   ##   #  ####  ######
#
####################################
---
kind: Service
apiVersion: v1
metadata:
  namespace: grafana
  name: prometheus
spec:
  selector:
    app: prometheus
  ports:
  - name: promui
    protocol: TCP
    port: 9090
    targetPort: 9090