apiVersion: v1
kind: Service
metadata:
  name: guestbook-frontend-service
spec:
  type: LoadBalancer
  selector:
    app: guestbook-frontend
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80