apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-frontend # this is the name returned when running kgp
spec:
  replicas: 1

  selector:
    matchLabels:
      app: guestbook-frontend

  template:
    metadata:
      labels:
        app: guestbook-frontend

    spec:
      containers:
      - name: guestbook-frontend
        image: docker.artifactory.euw.platformservices.io/bpe/guestbook-frontend:1.0.2
        ports:
        - containerPort: 80
        env:
        - name: CONFIG_FILE
          value: "/config/config.json"
        volumeMounts:
        - name: config-volume
          mountPath: /config
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"

      volumes:
        - name: config-volume
          configMap:
            name: guestbook-frontend-configmap
        
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: guestbook-frontend-configmap
data:
  config.json: |
    {"redis_master": "redis-master", "redis_slave": "redis-slave"}

---
apiVersion: v1
kind: Service
metadata:
  name: redis-master
spec:
  type: ClusterIP
  selector:
    app: redis-master
  ports:
  - name: http
    protocol: TCP
    port: 6379
    targetPort: 6379

---
apiVersion: v1
kind: Service
metadata:
  name: guestbook-frontend-service
spec:
  type: LoadBalancer
  selector:
    app: guestbook-frontend
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80