####################################
#
#   #     #                        
#   ##    #  ####  # #    # #    # 
#   # #   # #    # # ##   #  #  #  
#   #  #  # #      # # #  #   ##   
#   #   # # #  ### # #  # #   ##   
#   #    ## #    # # #   ##  #  #  
#   #     #  ####  # #    # #    #
#
####################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingress-example
  labels:
    app: ingress-example
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ingress-example
  template:
    metadata:
      labels:
        app: ingress-example
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
        resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits: 
              memory: "128Mi"
              cpu: "500m"
        volumeMounts:
        - name: html-volume
          mountPath: /usr/share/nginx/html
      volumes:
      - name: html-volume
        configMap:
          name: mysite-html

####################################
#
#     #####                                       
#    #     # ###### #####  #    # #  ####  ###### 
#    #       #      #    # #    # # #    # #      
#     #####  #####  #    # #    # # #      #####  
#          # #      #####  #    # # #      #      
#    #     # #      #   #   #  #  # #    # #      
#     #####  ###### #    #   ##   #  ####  ######
#
####################################
---
apiVersion: v1
kind: Service
metadata:
  name: ingress-example-service
spec:
  type: ClusterIP
  selector:
    app: ingress-example
  ports:
    - protocol: TCP
      port: 80

####################################
#
#   ###                                           
#    #  #    #  ####  #####  ######  ####   ####  
#    #  ##   # #    # #    # #      #      #      
#    #  # #  # #      #    # #####   ####   ####  
#    #  #  # # #  ### #####  #           #      # 
#    #  #   ## #    # #   #  #      #    # #    # 
#   ### #    #  ####  #    # ######  ####   ####  
#
####################################
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-example-ingress
  annotations:
    kubernetes.io/ingress.class: "traefik"
    traefik.frontend.rule.type: PathPrefixStrip
    # cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.frontend.passHostHeader: "false"
    ingress.kubernetes.io/protocol: http
spec:
  # tls:
  # - hosts:
  #   - test.kavanet.io
  #   secretName: test.kavanet.io-tls
  rules:
  # - host: kavanet.io
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ingress-example-service
            port: 
              number: 80
      - path: /test
        pathType: Prefix
        backend:
          service:
            name: ingress-example-service
            port: 
              number: 80
      - path: /boop
        pathType: Prefix
        backend:
          service:
            name: ingress-example-service
            port: 
              number: 80

####################################
#
#   #####                                   #     #               
#  #     #  ####  #    # ###### #  ####     ##   ##   ##   #####  
#  #       #    # ##   # #      # #    #    # # # #  #  #  #    # 
#  #       #    # # #  # #####  # #         #  #  # #    # #    # 
#  #       #    # #  # # #      # #  ###    #     # ###### #####  
#  #     # #    # #   ## #      # #    #    #     # #    # #      
#   #####   ####  #    # #      #  ####     #     # #    # #      
#
####################################
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysite-html
data:
  index.html: |
    <html>
      <head><title>Ingress Example</title>
        <style>
          html {
            font-size: 62.5%;
          }
          body {
            font-family: sans-serif;
            background-color: midnightblue;
            color: white;
            display: flex;
            flex-direction: column;
            justify-content: center;
            height: 100vh;
          }
          div {
            text-align: center;
            font-size: 8rem;
            text-shadow: 3px 3px 4px dimgrey;
          }
        </style>
      </head>
      <body>
        <div>Ingress Example</div>
      </body>
    </html>