kind: Deployment
apiVersion: apps/v1
metadata:
  name: hello-world
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
        - name: hello-world
          image: hello-world
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
                # requests:
                #   memory: "64Mi"
                #   cpu: "250m"
                limits:
                  memory: "128Mi"
                  cpu: "500m"
          restartPolicy: Always
---
kind: Service
apiVersion: v1
metadata:
  name: hello-world-entrypoint
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    nodePort: 31000
  selector:
    app: hello-world