kind: Deployment
apiVersion: apps/v1
metadata:
  name: create-react-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: create-react-app
  template:
    metadata:
      labels:
        app: create-react-app
        # something: name
    spec:
      containers:
        - name: create-react-app
          image: localhost:5000/create-react-app:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
      restartPolicy: Always
---
kind: Service
apiVersion: v1
metadata:
  name: create-react-app-entry-point
spec:
  selector:
    app: create-react-app
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    nodePort: 31000
  
